config/routes.rb
Merchant::Application.routes.draw do
  
  resources :static_pages
  resources :users
  resources :sessions
  resources :addresses
  resources :charges
  resources :products, except: [:destroy] 
  resources :order_items
  resources :orders do
    member do
      get :confirm
    end
  end
  root 'store#index', :as => "store"

  get 'pay_now' => 'orders#pay_now'
  
  get "logout" => "sessions#destroy", as: "logout", via: :get
  get "login" => "sessions#new", as: "login", via: :get
  get "signup" => "users#new", as: "signup", via: :get

  get "about" => "static_pages#about", as: "about"
  get "contact" => "static_pages#contact", as: "contact"

  get 'browse/shoes' => 'products#shoes'
  get 'browse/foods' => 'products#foods'
  get 'browse/clothes' => 'products#clothes'
  get 'browse/cities' => 'products#cities'
end

  

app/models/order.rb
class Order < ActiveRecord::Base
  
  has_many :order_items, dependent: :destroy
  belongs_to :address
  belongs_to :user
  # validates_presence_of :order_items
  validate :has_items, on: :update

  


  def has_items
    unless self.order_items.count > 0
      errors.add(:order_items, "Must have item before checking out!")
    end
  end


  def total
    self.order_items.map do |i| 
      i.subtotal 
    end.sum
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  #before_action :require_login, only: [:show]
  before_action :set_order, only: [:edit, :update, :destroy, :confirm]
  
  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end

  def show
    @order = current_user.current_cart
  end

  def edit
  end

  def create
    @user = current_user
    @order = @user.orders.build(order_params)
    # @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Successfully added product to cart.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new'}
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        @order.status = "Order is submitted"
        @order.save
        format.html { redirect_to confirm_order_path(@order), notice: "Horray, your order is successfully submitted." }
        format.json { head :no_content }
      else
        format.html { render action: 'show' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to products_path }
      format.json { head :no_content }
    end
  end

  def confirm
    @user = current_user
    UserMailer.order_confirmation(@user, @order).deliver
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:user_id, :status, :address_id)
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/confirm.html.erb
<h3>Thanks for shopping at Local Makers</h3>

<div data-alert="" class="alert-box secondary">
  Your following order has been submitted!.
</div>
<table>
  <thead>
    <tr>
      <th width="200">Image</th>
      <th width="200">Title</th>
      <th width="80">Quantity</th>
      <th width="90">Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <% @order.order_items.each do |item| %>
    <tr>
      <td><%= image_tag item.product.image_url(:small_thumb).to_s %></td>
      <td><%= item.product.title %></td>
      <td><%= item.quantity %></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td><strong><%= print_price @order.total %></strong></td>
    </tr>
  <% end %>
<p>has been submitted!</p>

  </tbody>
</table>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user_id %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Order', new_order_path %></p>
<p> <%= link_to "Continue Shopping", store_path %> </p>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/pay_now.html.erb
<%= form_tag pay_now_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="local merchant purchase"
          data-amount="500"></script>
<% end %>

app/views/orders/show.html.erb
  <h1>Your Order</h1>

  <%= form_for @order do |f| %>
   <table class="table-center">
      <tr>
        <th>Name</th>
        <td><%= @order.user.name if @order.user %></td>
      </tr>
      <tr>
        <th>Order Status:</th>
        <% if @order.status == nil %>
        <td>Not submitted</td>
        <% else %>
        <td><%= @order.status %></td>
        <% end %>
      </tr>
      <tr>
        <th>Items:</th>
        <td><%= @order.order_items.count %></td>
      </tr>
      <tr>
        <th>Items</th>
        <th>Title</th>
        <th>Quantity</th>
        <th colspan="2">Stock</th>
        <th>Unit Price</th>
        <th>Subtotal</th>
        
        <th>Delete</th>
      </tr>
      <tr>
      <% @order.order_items.each do |item| %>
        <tr>
          <td><%= image_tag item.product.image_url(:thumb).to_s %></td>
          <td><%= item.product.title %></td>
          <td><%= link_to item.quantity, edit_order_item_path(item) %></td>
          <td colspan="2"><%= display_stock item.product.stock, item.quantity %></td>
          <td><%= print_price item.product.price %></td>
          <td><%= print_price item.subtotal %></td>
          <td><%= link_to "Delete", item, data: {confirm: "Are you sure?"}, method: :delete ,class: "button alert" %></td>
        </tr>
      <% end %>
        <tr>
          <% if current_user != nil %>
          <th>Shipping To:</th>
          <th colspan="5">
            <%= link_to (f.select :address_id, current_user.addresses.collect{|a| [a.to_s, a.id]}), class: "button alert round split" %>
            <%= f.hidden_field :address_id %>
            Or, <%= link_to "Add new address", new_address_path %>
          </th>
          <th><%= print_price @order.total %></td>
          <th colspan="2">is your Total</th>
        </tr>
        <tr> 
          <th colspan="8">
          <form action="" method="PUT">
            <script
              src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
              data-key="pk_test_E2bnXMdsBwJq9msYABBBm4gh"
              data-amount=<%="#{@order.total * 100}"%>
              data-name="local merchant"
            </script>
          </form>
          </th>
           <% else %>
            <p>Please sign in to submit!</p>
          <% end %>
        </tr>
    </table>
  <% end %>



  <ul class="inline-list">
    <li class=""><%= link_to "Empty Cart", @order, data: { confirm: 'Are you sure?' }, method: :delete, class: "button" %></li>
    <li class=""><%= link_to "Continue Shopping", store_path, class: "button success" %></dd></li>
  </ul>