config/routes.rb
Merchant::Application.routes.draw do
  
  resources :static_pages
  resources :users
  resources :sessions
  resources :addresses
  resources :charges
  resources :products, except: [:destroy] 
  resources :order_items
  resources :orders do
    member do
      get :confirm
    end
  end
  root 'store#index', :as => "store"

  get 'pay_now' => 'orders#pay_now'
  
  get "logout" => "sessions#destroy", as: "logout", via: :get
  get "login" => "sessions#new", as: "login", via: :get
  get "signup" => "users#new", as: "signup", via: :get

  get "about" => "static_pages#about", as: "about"
  get "contact" => "static_pages#contact", as: "contact"

  get 'browse/shoes' => 'products#shoes'
  get 'browse/foods' => 'products#foods'
  get 'browse/clothes' => 'products#clothes'
  get 'browse/cities' => 'products#cities'
end

  

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates_numericality_of :quantity, :greater_than => 0
  validates_presence_of :order_id, :product_id

  def subtotal
    Product.find(self.product_id).price.to_s.to_d * quantity.to_s.to_d
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :load_order, only: [:create]

  def index
    @order_items = OrderItem.all
  end

  def new
    @order_item = OrderItem.new
  end

  def edit
  end

  def show
  end

  def create
    if current_user
      @order_item = current_user.current_cart.order_items.find_or_initialize_by_product_id(params[:product_id])
      @order_item.quantity +=1
      respond_to do |format|
        if @order_item.save 
          format.html { redirect_to current_user.current_cart, notice: 'Successfully added product to cart.' }
          format.json { render action: 'show', status: :created, location: @order_item }
        else
          format.html { render action: 'new' }
          format.json { render json: @order_item.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to login_path
    end
  end

  def update
    @order_item = OrderItem.find(params[:id])
    respond_to do |format|
      if order_item_params[:quantity].to_i == 0
        @order_item.destroy
        format.html { redirect_to @order_item.order, notice: 'Item was deleted from your cart.' }
        format.json { head :no_content }
      elsif @order_item.update(order_item_params)
        format.html { redirect_to @order_item.order, notice: 'Successfully updated the order item.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to @order_item.order, notice: "Your #{@order_item.product.title} was deleted!" }
      format.json { head :no_content }
    end
  end

  private
  def set_item
    @order_item = OrderItem.find(params[:id])
  end

  def order_item_params
    params.require(:order_item).permit(:product_id, :order_id, :quantity) 
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_form.html.erb
<%= form_for(@order_item) do |f| %>
  <% if @order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% @order_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>* Your are editing quantity of <strong> <%= @order_item.product.title %> </strong></p>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<h3>Update Order quantity</h3>

<%= render 'form' %>

<%= link_to 'Oh forget it, I am happy with the quantity' , order_item_path %>

app/views/order_items/index.html.erb
<h1>Listing order_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Order</th>
      <th>Quantity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.product_id %></td>
        <td><%= order_item.order_id %></td>
        <td><%= order_item.quantity %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New order_item</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p>
  <strong>Product:</strong>
  <%= @order_item.product.title %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>