config/routes.rb
Merchant::Application.routes.draw do
  
  resources :static_pages
  resources :users
  resources :sessions
  resources :addresses
  resources :charges
  resources :products, except: [:destroy] 
  resources :order_items
  resources :orders do
    member do
      get :confirm
    end
  end
  root 'store#index', :as => "store"

  get 'pay_now' => 'orders#pay_now'
  
  get "logout" => "sessions#destroy", as: "logout", via: :get
  get "login" => "sessions#new", as: "login", via: :get
  get "signup" => "users#new", as: "signup", via: :get

  get "about" => "static_pages#about", as: "about"
  get "contact" => "static_pages#contact", as: "contact"

  get 'browse/shoes' => 'products#shoes'
  get 'browse/foods' => 'products#foods'
  get 'browse/clothes' => 'products#clothes'
  get 'browse/cities' => 'products#cities'
end

  

app/models/product.rb
class Product < ActiveRecord::Base

  #validations order is ipmortant for view 
  validates_uniqueness_of :title
  validates_length_of :title, :minimum => 5
  validates_presence_of :title, :description, :image, :price, :stock
  validates_numericality_of :price, :greater_than_or_equal_to => 0.01
  validates_numericality_of :stock, :greater_than_or_equal_to => 0
  # validates_format_of :image_url, :with => /\.(gif|jpg|png)\z/i

  before_destroy :ensure_not_accossiated_to_any_order_item   
  has_many :order_items
  belongs_to :user
  belongs_to :category
  mount_uploader :image, ImageUploader
  default_scope :order => 'title'
 
  CATEGORIES = ["food", "shoes", "clothes"]

  def price=(input)
		input.delete!("$")
		super
  end
  
  def ensure_not_accossiated_to_any_order_item
    if order_items.empty?
      return true
    else
      errors.add :base, "You can not delete that becasue its assocciated to an item(s)."
      return false
    end
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :set_product, only: [:show, :edit, :update, :destroy]
  #before_filter :require_login, :only => @product

  def index

  	# @products = Product.where(user_id: current_user.id)
    @products = current_user.products
    # @products = Product.search(params[:search])
  end

  def show
  end

  def new
  	@product = Product.new
  end

  def edit
  end

  def create
  	@product = Product.new(product_params)
    @product.user = current_user
  	respond_to do |format|
	  	if@product.save
        params[:product][:user_id] = current_user.id
	  		format.html { redirect_to @product, notice: 'Product weas successfully created.' }
	  		format.json { render action: 'show', status: :created, location: @product }
	  	else
	  		format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
	  	end
  	end
  end

  def update
  	respond_to do |format|
  		if @product.update(product_params)
  			format.html { redirect_to @product, notice: 'product was successfully updated.' }
  			format.json { head :no_content }
  		else
  			format.html { render action: 'edit' }
  			format.json { render json: @product.errors, status: :unprocessable_entity}
   		end
  	end
  end

  def destroy
  end

  def shoes
    @products = Product.where("category_name = ?", "shoes")
  end

  def foods
    @products = Product.where("category_name = ?", "food")
  end

  def clothes
    @products = Product.where("category_name = ?", "clothes")
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
  	@product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  # This tells Rails to allow all four of our Product attributes to be mass-assign-able.
  def product_params
  	params.require(:product).permit(:title, :description, :price, :image, :stock, :category_name, :search )
  end
end

app/helpers/products_helper.rb
module ProductsHelper
	
	# price helper method
	def print_price(price)
		number_to_currency price
	end

	# stock helper
	def display_stock(stock, requested = 1)
		if stock == 0
			content_tag :span, "Out of Stock"
		elsif stock >= requested
			content_tag :span, "In stock (#{stock}) "
		else
			content_tag :span, "Insufficient stock (#{stock})"
		end
	end
end

app/views/products/_form.html.erb
<%= form_for @product, :html => {:multipart => true} do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prevent this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
	<% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description,  :rows => 6 %>
  </div>
  
  <div class="field">
  	<%= f.label :price, "Price (like 2.99)" %><br>
  	<%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :stock, " How many item you want to sell?" %><br>
    <%= f.text_field :stock %>
  </div> 
  
  <div class="field">
    <%= f.label :category_name, "Category" %><br />
    <%= f.select :category_name, Product::CATEGORIES ,prompt: 'Select a category' %>
  </div>
 
  <div class="field">
    <%= f.file_field :image %>
  </div>
  
  <div class="actions"><%= f.submit %></div>

<% end %>

app/views/products/clothes.html.erb
<h1>clothes</h1>

<% @products.each do |product| %>
  <div>
    <p><%= image_tag product.image_url(:thumb).to_s %></p>
    <h3><%= product.title %></h3>    
    <p><%= product.description %></p>
    <span><strong><%= print_price(product.price) %></strong></span><br>
    <span><%= button_to "Add to Cart", order_items_path(product_id: product .id) %></span> 
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit your product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %>
<%= link_to 'Back', products_path %>

app/views/products/foods.html.erb
<h1>Foods</h1>

<% @products.each do |product| %>
  <div>
    <p><%= image_tag product.image_url(:thumb).to_s %></p>
    <h3><%= product.title %></h3>    
    <p><%= product.description %></p>
    <span><strong><%= print_price(product.price) %></strong></span><br>
    <span><%= button_to "Add to Cart", order_items_path(product_id: product .id) %></span> 
  </div>
<% end %>

app/views/products/index.html.erb
<div class="row">
    <div class="tewlve columns">
      <h2 class="light-weight">Local Makers Products</h2>
    </div>
  </div>

<div class="row">
    <div class="tewlve columns">
      <ul class="product block-grid products four-up">
      	<% @products.each do |product| %>
          
        <li>
            <span class="top local_maker"><%= image_tag product.image_url(:thumb).to_s %></span>
            <h3 class="local_maker"><%= link_to product.title, product_path(product) %></h3>
            <p><%= truncate(strip_tags(product.description), :length => 250 )%></p>
            <h6 class="about"><%= print_price(product.price) %></h6>
            <%= link_to "Show", product_path(product), class: "secondary small button radius" %>
				  	<%= link_to 'Edit', edit_product_path(product), class: "secondary small button radius" %><br> 
          <hr>
        </li>
      <% end %>
    </ul>
      
    </div>
    <p> <%= link_to "Create a New Product", new_product_path, class: "button success button-wrap" %> </p>
  </div>

app/views/products/new.html.erb
<h2>Add new product</h2>

<%= render 'form' %>

<%= link_to "Back", products_path %>

app/views/products/shoes.html.erb
<h1>shoes</h1>

<% @products.each do |product| %>
  <div>
    <p><%= image_tag product.image_url(:thumb).to_s %></p>
    <h3><%= product.title %></h3>    
    <p><%= product.description %></p>
    <span><strong><%= print_price(product.price) %></strong></span><br>
    <span><%= button_to "Add to Cart", order_items_path(product_id: product .id) %></span> 
    
  </div>
<% end %>

app/views/products/show.html.erb
      <div class="thumbnail-style">
        <div class="thumbnail-img">
          <div>
            <%= image_tag @product.image_url(:thumb).to_s %>
          </div>
          <%= link_to "Add to Cart", order_items_path(product_id: @product.id), class: "btn-more hover-effect", method: :post %>         
        </div>
        <h3><a class="hover-effect" ><%= @product.title %></a></h3>
        <p><%= @product.description %></p>
        
        <span class="panel"><%= print_price(@product.price) %></span>

         <p> <% if current_user && (current_user.id == @product.user_id) %>
          <span class="panel"><%= link_to 'Edit', edit_product_path(@product) %> 
          <% end %>
          </p>
          <p> <%= link_to 'Back', products_path %></p>
      </div>