config/routes.rb
Merchant::Application.routes.draw do
  
  resources :static_pages
  resources :users
  resources :sessions
  resources :addresses
  resources :charges
  resources :products, except: [:destroy] 
  resources :order_items
  resources :orders do
    member do
      get :confirm
    end
  end
  root 'store#index', :as => "store"

  get 'pay_now' => 'orders#pay_now'
  
  get "logout" => "sessions#destroy", as: "logout", via: :get
  get "login" => "sessions#new", as: "login", via: :get
  get "signup" => "users#new", as: "signup", via: :get

  get "about" => "static_pages#about", as: "about"
  get "contact" => "static_pages#contact", as: "contact"

  get 'browse/shoes' => 'products#shoes'
  get 'browse/foods' => 'products#foods'
  get 'browse/clothes' => 'products#clothes'
  get 'browse/cities' => 'products#cities'
end

  

app/models/address.rb
class Address < ActiveRecord::Base

  # before_save :uppercase_fields

  # def uppercase_fields
  #   attributes.each_value{|value| value.upcase!}
  # end

  belongs_to :user
  has_many :orders

  canadian_postal_code = /[a-zA-Z]\d[a-zA-Z]()\d[a-zA-Z]\d/
  validates :postalcode, format: { with: canadian_postal_code }
  validates :postalcode, length: { is: 6 }
  validates :province, format: {with: /[A-Z]{2}/}
  validates_presence_of :line1, :line2, :city, :province, :postalcode

  def to_s
    [ line1, line2, "#{city}, #{province}, #{postalcode}"].compact.join(", ")
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products

	CATEGORIES = ["food", "shoes", "clothes", "toronto"]
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :prodcut
  belongs_to :cart
end

app/models/order.rb
class Order < ActiveRecord::Base
  
  has_many :order_items, dependent: :destroy
  belongs_to :address
  belongs_to :user
  # validates_presence_of :order_items
  validate :has_items, on: :update

  


  def has_items
    unless self.order_items.count > 0
      errors.add(:order_items, "Must have item before checking out!")
    end
  end


  def total
    self.order_items.map do |i| 
      i.subtotal 
    end.sum
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates_numericality_of :quantity, :greater_than => 0
  validates_presence_of :order_id, :product_id

  def subtotal
    Product.find(self.product_id).price.to_s.to_d * quantity.to_s.to_d
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  #validations order is ipmortant for view 
  validates_uniqueness_of :title
  validates_length_of :title, :minimum => 5
  validates_presence_of :title, :description, :image, :price, :stock
  validates_numericality_of :price, :greater_than_or_equal_to => 0.01
  validates_numericality_of :stock, :greater_than_or_equal_to => 0
  # validates_format_of :image_url, :with => /\.(gif|jpg|png)\z/i

  before_destroy :ensure_not_accossiated_to_any_order_item   
  has_many :order_items
  belongs_to :user
  belongs_to :category
  mount_uploader :image, ImageUploader
  default_scope :order => 'title'
 
  CATEGORIES = ["food", "shoes", "clothes"]

  def price=(input)
		input.delete!("$")
		super
  end
  
  def ensure_not_accossiated_to_any_order_item
    if order_items.empty?
      return true
    else
      errors.add :base, "You can not delete that becasue its assocciated to an item(s)."
      return false
    end
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :first_name, :last_name, :username
  validates_uniqueness_of :email, :username

  has_many :products
  has_many :addresses
  has_many :orders
  
  def name
    return "#{first_name} #{last_name}"
  end

  def current_cart
    self.orders.where(status: nil).first_or_create
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  #before_action :require_login, only: [:show]
  before_action :set_order, only: [:edit, :update, :destroy, :confirm]
  
  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end

  def show
    @order = current_user.current_cart
  end

  def edit
  end

  def create
    @user = current_user
    @order = @user.orders.build(order_params)
    # @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Successfully added product to cart.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new'}
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        @order.status = "Order is submitted"
        @order.save
        format.html { redirect_to confirm_order_path(@order), notice: "Horray, your order is successfully submitted." }
        format.json { head :no_content }
      else
        format.html { render action: 'show' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to products_path }
      format.json { head :no_content }
    end
  end

  def confirm
    @user = current_user
    UserMailer.order_confirmation(@user, @order).deliver
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:user_id, :status, :address_id)
  end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  
  def index
    @products = Product.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    # @users = User.find(params[:id])
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.registration_confirmation(@user).deliver
      auto_login(@user)
      redirect_to store_url, notice: "Signed Up!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(user_params)
       redirect_to @user, notice: 'User was successfully updated.' 
       render action: "edit"
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  

  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	
	# price helper method
	def print_price(price)
		number_to_currency price
	end

	# stock helper
	def display_stock(stock, requested = 1)
		if stock == 0
			content_tag :span, "Out of Stock"
		elsif stock >= requested
			content_tag :span, "In stock (#{stock}) "
		else
			content_tag :span, "Insufficient stock (#{stock})"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cats.erb
<ul class="side-nav">
  <h4>Category</h4>
  <li class="divider"></li>
  <li><%= link_to "Shoes", browse_shoes_path %></li>
  <li><%= link_to "Foods", browse_foods_path %></li>
  <li><%= link_to "Clothes", browse_clothes_path %></li>
</ul>

app/views/layouts/_copyright.erb
      <div class="span8">           
        <p>2013 &copy; Those Who Makes. <%= link_to "Home", store_path %> </p>                
      </div>

app/views/layouts/_footer.erb
      <div class="span4">
        <div class="headline"><h3>Contact Us</h3></div> 
          <address>
            1000 Young Street <br />
            Toronto, ON <br />
            Canada <br />
            Phone: 800 123 3456 <br />
            Email: <%= mail_to "suppport@localmerchant.com", "Support" %>
          </address>
      </div>

app/views/layouts/_info.erb
<!-- Information Blokcs -->
<div class="row-fluid margin-bottom-20">
  <div class="span8">
    <div class="headline"><h3>Welcome To UNIFY Template</h3></div>
    <p>
      <img class="pull-left lft-img-margin img-width-200" src="assets/img/carousel/6.jpg" alt="" />
        Unify is an incredibly beautiful responsive Bootstrap Template for corporate and creative professionals. It works on all major web browsers, tablets and phone.
    </p> 
      <ul class="unstyled">
        <li><i class="icon-ok color-green"></i> Donec id elit non mi porta gravida</li>
        <li><i class="icon-ok color-green"></i> Corporate and Creative</li>
        <li><i class="icon-ok color-green"></i> Responsive Bootstrap Template</li>
        <li><i class="icon-ok color-green"></i> Corporate and Creative</li>
      </ul><br />
      <blockquote class="hero-unify">
          <p>Award winning digital agency. We bring a personal and effective approach to every project we work on, which is why. Unify is an incredibly beautiful responsive Bootstrap Template for corporate professionals.</p>
          <small>CEO, Jack Bour</small>
      </blockquote>
  </div>
  <!--/span8-->        
  <!-- Latest Shots -->
  <div class="span4">
    <div class="headline"><h3>Latest Shots</h3></div>
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <img src="assets/img/carousel/5.jpg" alt="" />
          <div class="carousel-caption">
            <p>Cras justo odio, dapibus ac facilisis in, egestas.</p>
          </div>
        </div>
        <div class="item">
          <img src="assets/img/carousel/4.jpg" alt="" />
          <div class="carousel-caption">
            <p>Cras justo odio, dapibus ac facilisis in, egestas.</p>
          </div>
        </div>
        <div class="item">
          <img src="assets/img/carousel/3.jpg" alt="" />
          <div class="carousel-caption">
            <p>Cras justo odio, dapibus ac facilisis in, egestas.</p>
          </div>
        </div>
      </div>      
      <div class="carousel-arrow">
          <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="icon-angle-left"></i></a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="icon-angle-right"></i></a>
      </div>
    </div>
  </div><!--/span4-->
</div><!--/row-fluid--> 
<!-- //End Information Blokcs -->

app/views/layouts/_intro.erb
<!--=== Purchase Block ===-->
<div class="row-fluid purchase margin-bottom-30">
  <div class="container">
    <div class="span9">
      <span>Welcome to local makers place where you only can buy local products.</span>
      <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi  vehicula sem ut volutpat. Ut non libero magna fusce condimentum eleifend enim a feugiat.</p>
    </div>
    <%= link_to "Products", products_path, class: "btn-buy hover-effect" %>
  </div>
</div><!--/row-fluid-->
<!-- End Purchase Block -->

app/views/layouts/_js.erb
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init();
        App.initSliders();
        Index.initParallaxSlider();
    });
</script>
<!--[if lt IE 9]>
    <script src="respond.js"></script>
<![endif]-->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29166220-1']);
  _gaq.push(['_setDomainName', 'htmlstream.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/_notices.erb
<% flash.each do |name, msg| %>
<div data-alert="" class="alert-box success">
  
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  
  <a href="" class="close">×</a>
</div>
<% end %> 

app/views/layouts/_styles.erb
  <%= stylesheet_link_tag "http://code.jquery.com/jquery-migrate-1.2.1.min.js", media: "all" %>
  <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
  <%= favicon_link_tag 'favicon.ico' %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    
  <link href='http://fonts.googleapis.com/css?family=Karla' rel='stylesheet' type='text/css'> 
  <link href='http://fonts.googleapis.com/css?family=Paytone+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Leckerli+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Maven+Pro:400,500' rel='stylesheet' type='text/css'>
  <link href="http://fonts.googleapis.com/css?family=Sansita+One" rel="stylesheet" type="text/css"/>
  <link href='http://fonts.googleapis.com/css?family=Changa+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Gochi+Hand' rel='stylesheet' type='text/css'>    
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800' rel='stylesheet' type='text/css'>

app/views/layouts/_top.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Those Who Makes", store_path %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Browse Products", products_path %></li>
      <li class="divider"></li>
      <% if current_user %>
      <li><%= link_to "Cart", current_user.current_cart %></li>
      <% end %>
      
      <% if current_user %>
        <li><%= link_to "Welcome, #{current_user.first_name.capitalize}", current_user %></li>
        <li><%= link_to "Signout", logout_path, class: "" %></li> 
      <% else %>
        <li><%= link_to "Signup", signup_path, class: "" %></li> 
        <li class="devider">&nbsp;</li>
        <li><%= link_to "Signin", login_path, class: "" %></li>
      <% end %>
    </ul>
  </div>
</nav>


<div class="row">
  <div class="large-12 columns">
<% form_tag products_path, :method => 'get' do %>
<ul class="right">
  <li class="search">
    <form>
      <%= text_field_tag :search, params[:search], class: 'span3', placeholder: 'Search' %>
    </form>
  </li>

  <li class="has-button">
    <%= submit_tag "Go", class: 'small button' %>
  </li>
</ul>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Thoe Who Make" %></title>

  	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag :modernizr %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/styles' %>
  </head>
  <body>
    <%= render 'layouts/top' %>
    <div class="row">      
      <div class="large-10 columns">
        <%= render 'layouts/notices' %>
        <%= yield %>
      </div>
      <div class="large-2 columns">
        <%= render 'layouts/cats' %> 
      </div>      
      <%= render 'layouts/js' %>
      <%= javascript_include_tag "application" %>        
    </div>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>